### ISSUE TITLE
Installation of the package

### ISSUE THREAD

**Issue by yossioo** [ROBOTIS-GIT/ROBOTIS-MANIPULATOR-H#12]
Hello!

I'm trying to install specified ROS Manipulator H package and I encounter errors of dependencies.
Screenshot attached.

Briefly: Error installing ros-kinetic-manipulator-h - unmet dependencies.
ros-kinetic-manipulator-h-base-module, ros-kinetic-manipulator-h-manager are not installable.

<img width="603" alt="manipuh" src="https://cloud.githubusercontent.com/assets/10714585/21760672/942890e8-d656-11e6-81b7-a813140b6335.png">

**Comment by s-changhyun** [comment]
Sorry for late response.
As you know, our package is incomplete and cannot possible to install using 'sudo apt-get'.
Please download from 'git clone'. 
Additionally, you will need ROBOTIS-FRAMEWORK.
