### ISSUE TITLE
Packages Have Unmet Dependencies

### ISSUE THREAD

**Issue by katmando** [ROBOTIS-GIT/ROBOTIS-MANIPULATOR-H#13]
I am trying to install the package for the manipulator however i keep receiving errors that im not sure how to handle.  After using the command:

sudo apt-get install ros-kinetic-manipulator-h ros-kinetic-robotis* ros-kinetic-qt-build

I receive the error:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 ros-kinetic-robotis-framework : Depends: ros-kinetic-robotis-controller but it is not installable
E: Unable to correct problems, you have held broken packages.

Any information on how to solve this would be greatly appreciated.

**Comment by JianXingChen** [comment]
i got the same problem

**Comment by katmando** [comment]
@JianXingChen the ROS packages for the manipulator is incomplete.  You need to add some more dependencies to the same directory.  You need to find and install packages such as ROBOTIS-Math, std_msgs,DynamixelSDK,ROBOTIS-Framework and a few others.  Once you have all of them it should work.

Although, i am still having issues using roslaunch for some of the packages.  Im still really new to ros so it could be an error on my part.
![image1](https://cloud.githubusercontent.com/assets/26590353/24264840/d40814d0-0fbe-11e7-9fab-80165b5fa1d5.JPG)

**Comment by s-changhyun** [comment]
Sorry for late response.
As you know, our package is incomplete and cannot possible to install using 'sudo apt-get'.
Please download from 'git clone'. 
Additionally, you will need ROBOTIS-FRAMEWORK.
