### ISSUE TITLE
broken package라고 하면서 패키지가 깔리지 않습니다!!!

### ISSUE THREAD

**Issue by wonchul-kim** [ROBOTIS-GIT/ROBOTIS-MANIPULATOR-H#15]
안녕하세요, manipulator-h를 사용하고 있는 유저입니다. 

sudo apt-get install ros-kinetic-manipulator-h ros-kinetic-robotis* ros-kinetic-qt-build

를 실행하였으나, broken package라고 하며 설치가 되지 않습니다. 

저는 ubuntu 16.04를 사용하고 있습니다. (ROS kinetic을 설치하였고, ros로 다른 플랫폼은 돌리는데 문제없었습니다.)

**Comment by s-changhyun** [comment]
현재, 저희 패키지는 정식등록이 제대로 되어있지않습니다.
sudo apt를 이용한 설치말고, 직접 여기서 소스코드를 받아서 쓰시는 것을 추천드립니다.
감사합니다.

**Comment by wonchul-kim** [comment]
소스 코드를 다운받아 해보앗지만 마찬가지로 에러가 뜨면서 컴파일이 되지 않습니다. 제가 지금 밖이라 무슨 에러엿는지는 기억이 나지
않지만 컨트롤 어쩌구 하면서 에러가 낫엇습니다

**Comment by s-changhyun** [comment]
이 패키지만 받아서 인스톨할경우에는 에러가 납니다.
추가로 ROBOTIS-FRAMEWORK, ROBOTIS-FRAMEWORK-msgs, ROBOTIS-MATH, DYNAMIXEL-SDK 패키지를 같이 동반할 필요가 있습니다.
어떤 메세지가 뜨는지 알려주시면 도와드리겠습니다.

**Comment by wonchul-kim** [comment]
말씀하신 패키지들은 어떻게 동반해야하나요???

2017-04-21 10:01 GMT+09:00 Changhyun Sung <notifications@github.com>:

**Comment by s-changhyun** [comment]
ROBOTIS-GIT에 있는거 다운받으시고,
같은 catkin_ws 폴더에 넣고 같이 컴파일 하시면 됩니다.

**Comment by wonchul-kim** [comment]
감사합니다! 덕분에 wiki에 나와있는 부분까지 성공하였습니다.

여쭈고 싶은 부분이 있는데 Rviz나 Gazebo로 하여금 시뮬레이션만 돌리려고 하는데 어떻게 해야하는지 알려주실 수 있으신가요?
(혹은 튜토리얼이 있는지 알려주시면 감사하겠습니다.)

시뮬레이션으로 학습 알고리즘을 돌리고 실험을 하려고 합니다.



감사합니다.
김원철 드림


2017-04-21 14:50 GMT+09:00 Changhyun Sung <notifications@github.com>:

**Comment by s-changhyun** [comment]
https://github.com/ROBOTIS-GIT/ROBOTIS-Documents/wiki/How-to-execute-Gazebo

Gazebo 관련해서는 이부분을 참고해주시면 되겠습니다.
