### ISSUE TITLE
a driver package of manipulator h

### ISSUE THREAD

**Issue by wilsionhuang** [ROBOTIS-GIT/ROBOTIS-MANIPULATOR-H#17]
Hi,sorry to trouble you.I'm just confused that when i use the manipulator arm on moveit.i should have a driver package to receive joint_state and publish the action server.but i can not find the driver package on the ROBOTIS -GIT/ROBOTIS-MANIPULATOR-H.so can you give me some advice about the driver?
Thanks!

**Comment by s-changhyun** [comment]
I think that sudo apt-get install has some error.
Please download the source in our GITHUB
