### ISSUE TITLE
manipulator_h_manager gazebo mode  fail

### ISSUE THREAD

**Issue by yossioo** [ROBOTIS-GIT/ROBOTIS-MANIPULATOR-H#22]
After fresh installation of following packages from git, 
>     DynamixelSDK
>     ROBOTIS-Framework
>     ROBOTIS-Framework-msgs
>     ROBOTIS-Math
>     ROBOTIS-MANIPULATOR-H (This Package)

A gazebo simulation launched by running the following command:
`roslaunch manipulator_h_gazebo manipulator_h_gazebo.launch `

When running a following command the manager starts but tries to connect via serial port, despite the fact that GAZEBO parameter specified to be true.
`roslaunch manipulator_h_manager manipulator_h_manager.launch gazebo:=true`

Trying to confirm that the argument was received, I added a line to CPP file:
>![screenshot_20170612_115221](https://user-images.githubusercontent.com/10714585/27026530-b7946cb2-4f66-11e7-8d68-e3935e4349e1.png)

The output when running the command:
![screenshot_20170612_120049](https://user-images.githubusercontent.com/10714585/27026592-efce8a5e-4f66-11e7-9a85-8baba8a1a5fd.png)

Full text:

> yo@MELAB4-PC11:~/catkin_ws$ roslaunch manipulator_h_manager manipulator_h_manager.launch gazebo:=true
> ... logging to /home/yo/.ros/log/0dfbcc18-4f4d-11e7-a84d-902b34d1e8de/roslaunch-MELAB4-PC11-19178.log
> Checking log directory for disk usage. This may take awhile.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://MELAB4-PC11:38485/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /gazebo: True
>  * /gazebo_robot_name: robotis_manipulat...
>  * /init_file_path: /home/yo/catkin_w...
>  * /offset_table: /home/yo/catkin_w...
>  * /robot_file_path: /home/yo/catkin_w...
>  * /rosdistro: kinetic
>  * /rosversion: 1.12.7
> 
> NODES
>   /
>     manipulator_h_manager (manipulator_h_manager/manipulator_h_manager)
> 
> ROS_MASTER_URI=http://localhost:11311
> 
> core service [/rosout] found
> process[manipulator_h_manager-1]: started with pid [19196]
> [ INFO] [1497257883.687906619]: manager->init
> [ WARN] [1497257883.690807721]: GAZEBO MODE = TRUE
> /dev/ttyUSB0 added. (baudrate: 1000000)
> [PortHandlerLinux::SetupPort] Error opening serial port!
> (/dev/ttyUSB0) [ID:  1] H54-200-S500-R added. 
> (/dev/ttyUSB0) [ID:  2] H54-200-S500-R added. 
> (/dev/ttyUSB0) [ID:  3] H54-100-S500-R added. 
> (/dev/ttyUSB0) [ID:  4] H54-100-S500-R added. 
> (/dev/ttyUSB0) [ID:  5]  H42-20-S300-R added. 
> (/dev/ttyUSB0) [ID:  6]  H42-20-S300-R added. 
> [ INFO] [1497257883.727269311]: Load offsets...
> 
>

**Comment by s-changhyun** [comment]
I think that there is no error.

[PortHandlerLinux::SetupPort] Error opening serial port!
-> if you execute gazebo mode, this is not error.

Did you try to use manipulator_h_gui? I think that command will work.
https://github.com/ROBOTIS-GIT/ROBOTIS-Documents/wiki/How-to-operate-GUI-program

**Comment by yossioo** [comment]
I can start GUI node and it works.

Why does port handler even start when I work with gazebo? 
If I have a real Manipulator-H connected, will it connect to it, despite the fact that I specify gazebo argument?
If so, how can I know whether the command I send will go to simulation in gazebo or to real robot?
If it won't connect, why it even tries to open serial port?

This looks deceiving: displaying a message about serial port when I work with gazebo, maybe some message about manager connecting to gazebo should be displayed instead?

**Comment by s-changhyun** [comment]
We will fix the framework.

If you start the framework with the topic "gazebo:=true",you can confirm from the command "rostopic list".
Some topics are generated for the gazebo.
