### ISSUE TITLE
안녕하세요, manipulator-h로 연구를 하고 있는 학생입니다. 

### ISSUE THREAD

**Issue by wonchul-kim** [ROBOTIS-GIT/ROBOTIS-MANIPULATOR-H#23]
안녕하세요, 연구를 하려는 도중에 여쭤볼게 있어서 이렇게 글을 남깁니다. 

현재 연구실에 UR3와 manipulator-h가 구비되어 있어 ur3로 gazebo로 하여금 시뮬레이션을 하였는데, 
link끼리의 충돌이나 주변 환경과의 충돌이 있을 경우 그냥 뚫고 지나가거나 억지로 관절을 한계이상으로 틀어서 joint angle이 이상해지고, 초기화 시켜도 돌아오지 않습니다. 

혹시 manipulator-H의 경우에는 gazebo로 시뮬레이션을 하게 되면, 링크(팔부분)끼리의 충돌이나 주변환경(땅이나 물건)과 충돌을 하게 되는 경우 알림(메세지나 토픽)을 주거나 특히 주변환경은 제가 코딩으로 하면 되지만 링크간의 충돌같은 경우에는 내부적으로 충돌하지 않도록 설계되어 있나요? 

김원철 드림

**Comment by s-changhyun** [comment]
안녕하세요.

먼저 내부적으로 충돌하지 않게 설계되어있는 메니퓰레이터는 존재하지 않을 것 같네요.

링크와 주변환경의 collision을 어떤식으로 체크하고 있는지 모르겠지만,
보통은 링크와 주변환경, 링크와 링크 (self-collision)의 collision은 같은 원리로 계산 가능합니다.
똑같이 코딩하셔야 됩니다.

Self-collision관련 참고논문 링크 한개 드립니다.
http://www.worldscientific.com/doi/abs/10.1142/S0219843610001976

**Comment by wonchul-kim** [comment]
답변 감사합니다.

그렇다면, 링크끼리 충돌하는 경우에 대해서 내부적으로 설계되어 있지 않다는 말씀이시죠?

혹시, 그렇다면 예를들어서 두 개의 링크가 완전히 접히는 경우는 그냥 겹쳐버리나요?


2017년 6월 26일 오후 4:35, Changhyun Sung <notifications@github.com>님이 작성:

**Comment by s-changhyun** [comment]
접히는 경우는 그냥 겹쳐버리는게 맞습니다.

바로 옆에 근접해 있는 경우의 self-collision은 보통 가동영역의 제한으로 막습니다.
