### ISSUE TITLE
Creating timer thread failed!!

### ISSUE THREAD

**Issue by gokul-narayanan1** [ROBOTIS-GIT/ROBOTIS-MANIPULATOR-H#25]
Whenever I run the manipulator_h_manager, the node fails throwing an error

>  Creating timer thread failed!!
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
 
How to fix this?

**Comment by s-changhyun** [comment]
Hi, I am sorry for late response.
You should execute manager as root (sudo bash).
