### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by wowfoot** [ROBOTIS-GIT/ROBOTIS-MANIPULATOR-H#26]
pls, check the following error
//////////////
$ sudo apt-get install ros-kinetic-manipulator-h
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-kinetic-manipulator-h

so, I tried git clone .. and catkin_make, which makes the following error.
///////////////
Scanning dependencies of target manipulator_h_manager
[ 97%] Building CXX object ROBOTIS-MANIPULATOR-H/manipulator_h_manager/CMakeFiles/manipulator_h_manager.dir/src/manipulator_h_manager.cpp.o
In file included from /home/shsong/ros/manipulator/src/ROBOTIS-MANIPULATOR-H/manipulator_h_manager/src/manipulator_h_manager.cpp:38:0:
/home/shsong/ros/manipulator/src/ROBOTIS-MANIPULATOR-H/manipulator_h_base_module/include/manipulator_h_base_module/base_module.h:58:54: fatal error: manipulator_h_base_module_msgs/JointPose.h: No such file or directory
compilation terminated.
ROBOTIS-MANIPULATOR-H/manipulator_h_manager/CMakeFiles/manipulator_h_manager.dir/build.make:62: recipe for target 'ROBOTIS-MANIPULATOR-H/manipulator_h_manager/CMakeFiles/manipulator_h_manager.dir/src/manipulator_h_manager.cpp.o' failed
make[2]: *** [ROBOTIS-MANIPULATOR-H/manipulator_h_manager/CMakeFiles/manipulator_h_manager.dir/src/manipulator_h_manager.cpp.o] Error 1
CMakeFiles/Makefile2:2252: recipe for target 'ROBOTIS-MANIPULATOR-H/manipulator_h_manager/CMakeFiles/manipulator_h_manager.dir/all' failed
make[1]: *** [ROBOTIS-MANIPULATOR-H/manipulator_h_manager/CMakeFiles/manipulator_h_manager.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

thank you for your reading.

**Comment by minhajfalaki** [comment]
hi, 
have you found the solution?
I have the same issue

**Comment by arbenton** [comment]
I've encountered this same issue. It should be noted that the individual packages are still available with `sudo apt ros-kinetic-manipulator-h-*`, but the metapackage is not available through `apt`, and the current version on github does not appear to build. 

**EDIT**:

The following packages are available:
- `ros-kinetic-manipulator-h-base-module-msgs`
- `ros-kinetic-manipulator-h-bringup`
- `ros-kinetic-manipulator-h-gazebo`
- `ros-kinetic-manipulator-h-gui`
- `ros-kinetic-manipulator-h-kinematics-dynamics`

This is missing `ros-kinetic-manipulator-h-manager`, which appears to be the package which catkin fails on.  

Interestingly, I was able to complete the build by installing what does exist through apt, and running `catkin_make`, but this build appears to have other issues.

**Comment by arbenton** [comment]
@s-changhyun, you appear to be the maintainer. Any ideas?

**Comment by s-changhyun** [comment]
@arbenton, 

Hi, I am sorry for late response.
I think that "sudo apt-get install ros-kinetic-manipulator-h" is a problem.
Our ROS official package has a problem.

Please try with only github's sourse.
(you should delete ROS official package).

**Comment by minhajfalaki** [comment]
Okey..  thanks for the reply..  i ll try that
