### ISSUE TITLE
manipulator_h_manager node crashing

### ISSUE THREAD

**Issue by gokul-narayanan1** [ROBOTIS-GIT/ROBOTIS-MANIPULATOR-H#30]
The manipulator_h_manager node crashes with the following error whenever I run it,

`
SUMMARY
========

PARAMETERS
 * /gazebo: False
 * /gazebo_robot_name: robotis_manipulat...
 * /init_file_path: /home/asimov/mani...
 * /offset_table: /home/asimov/mani...
 * /robot_file_path: /home/asimov/mani...
 * /rosdistro: kinetic
 * /rosversion: 1.12.13

NODES
  /
    manipulator_h_manager (manipulator_h_manager/manipulator_h_manager)

ROS_MASTER_URI=http://localhost:11311

process[manipulator_h_manager-1]: started with pid [14434]
[ INFO] [1525781629.963427602]: manager->init
/dev/ttyUSB0 added. (baudrate: 115200)
(/dev/ttyUSB0) [ID:  1] H54-100-S500-R added. 
(/dev/ttyUSB0) [ID:  4] H54-100-S500-R added. 
(/dev/ttyUSB0) [ID:  5] H54-100-S500-R added. 
(/dev/ttyUSB0) [ID: 10]  H42-20-S300-R added. 
(/dev/ttyUSB0) [ID:  2]  H42-20-S300-R added. 
(/dev/ttyUSB0) [ID: 17]  H42-20-S300-R added. 
[manipulator_h_manager-1] process has died [pid 14434, exit code -11, cmd /home/asimov/manipulatorh/devel/lib/manipulator_h_manager/manipulator_h_manager __name:=manipulator_h_manager __log:=/home/asimov/.ros/log/5523c050-528f-11e8-9c78-e8de270f8bfc/manipulator_h_manager-1.log].
log file: /home/asimov/.ros/log/5523c050-528f-11e8-9c78-e8de270f8bfc/manipulator_h_manager-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
'

How to fix this issue?

**Comment by routiful** [comment]
I think this issue would be help you. 

https://github.com/ROBOTIS-GIT/open_manipulator/issues/30#issuecomment-387370734

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
