### ISSUE TITLE
ROBOTIS-MANIPULATOR-H Documentation 

### ISSUE THREAD

**Issue by santdiego** [ROBOTIS-GIT/ROBOTIS-MANIPULATOR-H#31]
Hi. There is probably a problem with the documentation of the Robotis Manipulator H. First of all, the Denavit Hartemberg table is not very clear and may be incorrect. What do you mean by "DXL Angle"? .
In the "6.6 Mass Property" section, the COG z-position of some links exceeds the length of the link.

**Comment by yhna** [comment]
Hello, @santdiego 
First, There is a 135 degree rotation on the 3 joint as in "1.6 home position". Because of this, the origin angle of dxl is rotated.
Second, In the "6.6 Mass Property" section, the COG z-position is based on the "6.6.1 Coordinate".

**Comment by yhna** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
