### ISSUE TITLE
moveit with manipulator-H

### ISSUE THREAD

**Issue by Fred159** [ROBOTIS-GIT/ROBOTIS-MANIPULATOR-H#33]
Hello

We have manipualtor-H . 
It can be controlled with moveit pkg. 
We also want to combine sync the rviz visualization and gazebo visualization. How to do it ? 
I checked the moveit! manual-low level controller with ros-controller pkg. However, I found MANIPULATOR-H has no something like below.
`/panda_arm_controller/follow_joint_trajectory/goal
/panda_arm_controller/follow_joint_trajectory/feedback
/panda_arm_controller/follow_joint_trajectory/result
/hand_controller/gripper_action/goal
/hand_controller/gripper_action/feedback
/hand_controller/gripper_action/result`
Do you have any idea?

**Comment by yhna** [comment]
@Fred159 
Sorry for the late response.

See this E-Manual [link](http://emanual.robotis.com/docs/en/platform/manipulator_h/ros_example/#simulation) for how to use Manipulator-H with gazebo.
And a basic example of using Manipulator-H with MoveIt! is not provided.
