### ISSUE TITLE
Issues installing ROS package for ROBOTIS-MANIPULATOR-H

### ISSUE THREAD

**Issue by rob-pointcloud** [ROBOTIS-GIT/ROBOTIS-MANIPULATOR-H#6]
Hello,

  I have tried to install the packages without success so far.  I am on Ubuntu 16.04 and Ros kinetic
- I've tried the apt-get command, but it says "Unable to locate package ros-kinetic-manipulator-h
  ". Is there a location I need to add to my sources.list?
- I've tried installing via both git clone, and by downloading the file, and I get the same error during catkin_make, telling me "Could not find the required component 'qt_build'".  However this package does not appear to be available on ROS kinetic.

**Comment by s-changhyun** [comment]
about qt_build, please install this command.

sudo apt-get install ros-kinetic-qt-ros

**Comment by rob-pointcloud** [comment]
Thank you, that got me past the build error for qt_build.  I was able to get the ROBOTIS-MANIPULATOR-H code to compile, but also need to add the following Robotis folders to my catkin src directory:

ROBOTIS-Framework-msgs
ROBOTIS-MATH
DynamixelSDK
ROBOTIS-Framework
